FROM registry.access.redhat.com/ubi8/nodejs-14:1 AS BUILD_IMAGE

USER 65532:65532

WORKDIR /app
COPY ./package*.json ./
COPY ./app_pg.js ./
COPY ./public ./public
COPY ./src ./src
COPY ./migrations ./migrations

USER 0
RUN npm i

EXPOSE 8080
CMD ["node", "app_pg.js"]
