version: '3.8'

services:
  pqdb:
      container_name: pg_container
      image: postgres:14-alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test_db
      ports:
        - "5432:5432"
  mysql:
    container_name: mysql_container
    image: mysql:${MYSQL_VERSION:-8.0}
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME:-upperio_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-upperio_pwd}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME:-test_db}
    ports:
      - '3306:3306'
#  node-app:
#    container_name: app_mysql
#    build:
#      context: .
#      dockerfile: Dockerfile-mysql
#    ports:
#      - "8080:8080"
#    environment:
#      SERVICE_BINDING_ROOT: ./bindings
#    depends_on:
#      - "mysql"
