---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fruit-app-nodejs-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit-app-nodejs-mysql
  template:
    metadata:
      labels:
        app: fruit-app-nodejs-mysql
        deploymentconfig: fruit-app-nodejs-mysql
    spec:
      containers:
        - name: fruit-app-nodejs-mysql
          image: quay.io/myeung/fruit-app-nodejs-mysql:v0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fruit-app-nodejs-mysql
  name: fruit-app-nodejs-mysql
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fruit-app-nodejs-mysql
    deploymentconfig: fruit-app-nodejs-mysql
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: fruit-app-nodejs-mysql
  name: fruit-app-nodejs-mysql
spec:
  to:
    kind: Service
    name: fruit-app-nodejs-mysql
